version: "3"

services:
  database:
    image: oracle/database:19.3.0-se2
    container_name: database-test
    networks:
      - jira-bridge
    volumes:
      - database-data:/opt/oracle/oradata
      - $CURRENT_PATH/db_scripts/:/docker-entrypoint-initdb.d/setup
    environment:
      ORACLE_PWD: 'Oradoc_db1'
      ORACLE_CHARACTERSET: 'AL32UTF8'
      ENABLE_ARCHIVELOG: 'true'
    ports:
      - '1521'