version: "3"

services:
  database:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: y
      SA_PASSWORD: Qwerty01!
      MSSQL_PID: Enterprise
    networks:
      - jira-bridge
    container_name: database-test
    volumes:
      - database-data:/var/opt/mssql
      - $CURRENT_PATH/db_scripts/:/scripts/
      - $CURRENT_PATH/entrypoint.sh:/entrypoint/entrypoint.sh
    entrypoint: /bin/bash /entrypoint/entrypoint.sh