version: "3"

services:
  jira:
    environment:
      ATL_JDBC_URL: jdbc:mysql://address=(protocol=tcp)(host=database)(port=3306)/jiradb?sessionVariables=default_storage_engine=InnoDB
      ATL_JDBC_USER: jiradbuser
      ATL_JDBC_PASSWORD: pass
      ATL_DB_DRIVER: com.mysql.cj.jdbc.Driver
      ATL_DB_TYPE: mysql8
  database:
    image: mysql:8.0.17
    container_name: database-test
    volumes:
      - database-data:/var/lib/mysql
      - $CURRENT_PATH/db_scripts/:/docker-entrypoint-initdb.d/
      - $CURRENT_PATH/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty01!
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - jira-bridge
    cap_add:
      - SYS_NICE