version: "3"

services:
  database:
    image: mysql:8.0.17
    container_name: database-test
    volumes:
      - database-data:/var/lib/mysql
      - $CURRENT_PATH/db_scripts/:/docker-entrypoint-initdb.d/
      - $CURRENT_PATH/conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty01!
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysql" ,"-uroot", "-p$MYSQL_ROOT_PASSWORD", "-e", "\"SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'jiradb';\""]
      timeout: 5s
      retries: 12
    networks:
      - jira-bridge
    cap_add:
      - SYS_NICE