version: "3"

services:
  database:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: Qwerty01!
    networks:
      - jira-bridge
    container_name: database-test
    volumes:
      - database-data:/var/lib/postgresql/data
      - $CURRENT_PATH/db_scripts:/docker-entrypoint-initdb.d/