version: "3"

services:
  jira:
    environment:
      ATL_JDBC_URL: jdbc:postgresql://database:5432/jiradb
      ATL_JDBC_USER: jiradbuser
      ATL_JDBC_PASSWORD: pass
      ATL_DB_DRIVER: org.postgresql.Driver
      ATL_DB_TYPE: postgres72
  database:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: Qwerty01!
    networks:
      - jira-bridge
    container_name: database-test
    volumes:
      - database-data:/var/lib/postgresql/data
      - $CURRENT_PATH/db_scripts:/docker-entrypoint-initdb.d/
